global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'bootapp-letao-admin-exporter'
    metrics_path: '/actuator/prometheus' #指定抓取的路径
    static_configs:
      - targets: ['letao-admin:9999']
        labels:
          appname: 'bootapp-letao-admin'
          
  - job_name: 'bootapp-letao-app-exporter'
    metrics_path: '/actuator/prometheus' #指定抓取的路径
    static_configs:
      - targets: ['letao-app:9998']
        labels:
          appname: 'bootapp-letao-app'